I = 'EKMFLGDQVZNTOWYHXUSPAIBRCJQ'
II = 'AJDKSIRUXBLHWTMCQGZNPYFVOE'
III = 'BDFHJLCPRTXVZNYEIWGAKMUSQOV'
IV = 'ESOVPZJAYQUIRHXLNFTGKDCMWB'
V = 'VZBRGITYUPSDNHLXAWMJQOFECK'

UKW_A = 'EJMZALYXVBWFCRQUONTSPIKHGD'
UKW_B = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
UKW_C = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'