I = ['EKMFLGDQVZNTOWYHXUSPAIBRCJQ', 'Q']
II = ['AJDKSIRUXBLHWTMCQGZNPYFVOE', 'E']
III = ['BDFHJLCPRTXVZNYEIWGAKMUSQO', 'V']
IV = ['ESOVPZJAYQUIRHXLNFTGKDCMWB', 'J']
V = ['VZBRGITYUPSDNHLXAWMJQOFECK', 'Z']

UKW_A = 'EJMZALYXVBWFCRQUONTSPIKHGD'
UKW_B = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
UKW_C = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'