I = 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'
II = 'AJDKSIRUXBLHWTMCQGZNPYFVOE'
III = 'BDFHJLCPRTXVZNYEIWGAKMUSQO'
IV = 'ESOVPZJAYQUIRHXLNFTGKDCMWB'
V = 'VZBRGITYUPSDNHLXAWMJQOFECK'

UKW_A = 'EJMZALYXVBWFCRQUONTSPIKHGD'
UKW_B = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
UKW_C = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'